import string
str1 = "IT IS ORIENTED IN AN EAST- WEST ORIENTATION ALONG THE NORTH-SOUTH AXIS WHERE THE FRONT OF THE BUILDING IS FACING THE EAST. THE BUILDING IS LOCATED ON A SLOPE TOPOGRAPHY WHERE IT IS SITTING ON THE LOWEST GROUND FROM THE WEST TO THE EAST WHERE THE HIGHER GROUND IS."
print(str1.lower())